<?php
/**
 * This file is part of Railt package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
declare(strict_types=1);

namespace Serafim\Properties\Parser;

use Railt\Lexer\Factory;
use Railt\Lexer\LexerInterface;
use Railt\Parser\Driver\Llk;
use Railt\Parser\Driver\Stateful;
use Railt\Parser\Grammar;
use Railt\Parser\ParserInterface;
use Railt\Parser\Rule\Alternation;
use Railt\Parser\Rule\Concatenation;
use Railt\Parser\Rule\Repetition;
use Railt\Parser\Rule\Terminal;
use Railt\Parser\GrammarInterface;

/**
 * --- DO NOT EDIT THIS FILE ---
 *
 * Class BaseParser has been auto-generated.
 * Generated at: 20-10-2018 14:21:32
 *
 * --- DO NOT EDIT THIS FILE ---
 */
class BaseParser extends Stateful
{
    public const T_DOC_DEFINITION = 'T_DOC_DEFINITION';
    public const T_VARIABLE = 'T_VARIABLE';
    public const T_WORD = 'T_WORD';
    public const T_SUFFIX_ARRAY = 'T_SUFFIX_ARRAY';
    public const T_NAMESPACE = 'T_NAMESPACE';
    public const T_AND = 'T_AND';
    public const T_OR = 'T_OR';
    public const T_ANGLE_LEFT = 'T_ANGLE_LEFT';
    public const T_ANGLE_RIGHT = 'T_ANGLE_RIGHT';
    public const T_COMMA = 'T_COMMA';
    public const T_WHITESPACE = 'T_WHITESPACE';
    public const T_COMMENT = 'T_COMMENT';
    public const T_ANY = 'T_ANY';

    /**
     * Lexical tokens list.
     *
     * @var string[]
     */
    protected const LEXER_TOKENS = [
        self::T_DOC_DEFINITION => '@([\\w\\-]+)',
        self::T_VARIABLE => '\\$([a-zA-Z_\\x7f-\\xff][a-zA-Z0-9_\\x7f-\\xff]*)',
        self::T_WORD => '[a-zA-Z_\\x7f-\\xff][a-zA-Z0-9_\\x7f-\\xff]*',
        self::T_SUFFIX_ARRAY => '\\[\\]',
        self::T_NAMESPACE => '\\\\',
        self::T_AND => '&',
        self::T_OR => '\\|',
        self::T_ANGLE_LEFT => '<',
        self::T_ANGLE_RIGHT => '>',
        self::T_COMMA => ',',
        self::T_WHITESPACE => '\\s+',
        self::T_COMMENT => '\\*',
        self::T_ANY => '\\S+?',
    ];

    /**
     * List of skipped tokens.
     *
     * @var string[]
     */
    protected const LEXER_SKIPPED_TOKENS = [
        'T_WHITESPACE',
        'T_COMMENT',
        'T_ANY',
    ];

    /**
     * @var int
     */
    protected const LEXER_FLAGS = Factory::LOOKAHEAD;

    /**
     * List of rule delegates.
     *
     * @var string[]
     */
    protected const PARSER_DELEGATES = [
    ];

    /**
     * Parser root rule name.
     *
     * @var string
     */
    protected const PARSER_ROOT_RULE = 'Document';

    /**
     * @return ParserInterface
     * @throws \InvalidArgumentException
     * @throws \Railt\Lexer\Exception\BadLexemeException
     */
    protected function boot(): ParserInterface
    {
        return new Llk($this->bootLexer(), $this->bootGrammar());
    }

    /**
     * @return LexerInterface
     * @throws \InvalidArgumentException
     * @throws \Railt\Lexer\Exception\BadLexemeException
     */
    protected function bootLexer(): LexerInterface
    {
        return Factory::create(static::LEXER_TOKENS, static::LEXER_SKIPPED_TOKENS, static::LEXER_FLAGS);
    }

    /**
     * @return GrammarInterface
     */
    protected function bootGrammar(): GrammarInterface
    {
        return new Grammar([
            new Concatenation(0, ['DocBlock'], 'Document'), 
            new Concatenation(1, ['__any'], 'Document'), 
            new Alternation(2, [0, 1], null), 
            (new Repetition('Document', 0, -1, 2, null))->setDefaultId('Document'), 
            new Terminal(4, 'T_WORD', false), 
            new Terminal(5, 'T_DOC_DEFINITION', false), 
            new Terminal(6, 'T_VARIABLE', false), 
            new Terminal(7, 'T_SUFFIX_ARRAY', false), 
            new Terminal(8, 'T_NAMESPACE', false), 
            new Terminal(9, 'T_AND', false), 
            new Terminal(10, 'T_OR', false), 
            new Terminal(11, 'T_ANGLE_LEFT', false), 
            new Terminal(12, 'T_ANGLE_RIGHT', false), 
            new Terminal(13, 'T_COMMA', false), 
            new Alternation('__any', [4, 5, 6, 7, 8, 9, 10, 11, 12, 13], null), 
            new Repetition(15, 0, 1, 'TypeHint', null), 
            new Concatenation(16, ['DocBlockVariable'], null), 
            (new Concatenation('DocBlock', ['DocBlockTitle', 15, 16], 'DocBlock'))->setDefaultId('DocBlock'), 
            new Terminal(18, 'T_DOC_DEFINITION', true), 
            (new Concatenation('DocBlockTitle', [18], 'DocBlockTitle'))->setDefaultId('DocBlockTitle'), 
            new Terminal(20, 'T_VARIABLE', true), 
            (new Concatenation('DocBlockVariable', [20], 'DocBlockVariable'))->setDefaultId('DocBlockVariable'), 
            new Concatenation(22, ['__arrayTypeHint'], 'TypeHint'), 
            new Concatenation(23, ['__genericTypeHint'], 'TypeHint'), 
            new Concatenation(24, ['__scalarTypeHint'], 'TypeHint'), 
            new Alternation(25, [22, 23, 24], null), 
            new Repetition(26, 0, 1, '__typeHintContinuation', null), 
            (new Concatenation('TypeHint', [25, 26], null))->setDefaultId('TypeHint'), 
            new Concatenation(28, ['__typeHintDisjunction'], null), 
            new Alternation('__typeHintContinuation', ['__typeHintConjunction', 28], null), 
            new Terminal(30, 'T_OR', false), 
            new Concatenation('__typeHintDisjunction', [30, 'TypeHint'], 'Disjunction'), 
            new Terminal(32, 'T_AND', false), 
            new Concatenation('__typeHintConjunction', [32, 'TypeHint'], 'Conjunction'), 
            new Terminal(34, 'T_SUFFIX_ARRAY', false), 
            new Concatenation('__arrayTypeHint', ['__typeDefinition', 34], 'Array'), 
            new Terminal(36, 'T_ANGLE_LEFT', false), 
            new Repetition(37, 0, 1, '__genericArguments', null), 
            new Terminal(38, 'T_ANGLE_RIGHT', false), 
            new Concatenation('__genericTypeHint', ['__typeDefinition', 36, 37, 38], 'Generic'), 
            new Terminal(40, 'T_COMMA', false), 
            new Concatenation(41, [40, '__scalarTypeHint'], null), 
            new Repetition(42, 0, 1, 41, null), 
            new Concatenation('__genericArguments', ['__scalarTypeHint', 42], 'GenericArguments'), 
            new Concatenation('__scalarTypeHint', ['__typeDefinition'], 'Scalar'), 
            new Terminal(45, 'T_NAMESPACE', false), 
            new Repetition(46, 0, 1, 45, null), 
            new Terminal(47, 'T_WORD', true), 
            new Terminal(48, 'T_NAMESPACE', false), 
            new Terminal(49, 'T_WORD', true), 
            new Concatenation(50, [48, 49], null), 
            new Repetition(51, 0, -1, 50, null), 
            new Concatenation('__typeDefinition', [46, 47, 51], 'Type')
        ], static::PARSER_ROOT_RULE, static::PARSER_DELEGATES);
    }
}
